export const SUCCESS_FETCH_UNBILLED = 'SUCCESS_FETCH_UNBILLED';
export const FAIL_FETCH_UNBILLED = 'FAIL_FETCH_UNBILLED';
export const SUCCESS_SHOW_UNBILLED = 'SUCCESS_SHOW_UNBILLED';
export const FAIL_SHOW_UNBILLED = 'FAIL_SHOW_UNBILLED';
export const SUCCESS_FETCH_SERVICE_LINE = 'SUCCESS_FETCH_SERVICE_LINE';
export const FAIL_FETCH_SERVICE_LINE = 'FAIL_FETCH_SERVICE_LINE';
