export const SUCCESS_STORE_CREATE_FREE_AUCTION = 'SUCCESS_STORE_CREATE_FREE_AUCTION';
export const FAIL_STORE_CREATE_FREE_AUCTION = 'FAIL_STORE_CREATE_FREE_AUCTION';
export const SUCCESS_STORE_CREATE_ITEM_FREE_AUCTION = 'SUCCESS_STORE_CREATE_ITEM_FREE_AUCTION';
export const FAIL_STORE_CREATE_ITEM_FREE_AUCTION = 'FAIL_STORE_CREATE_ITEM_FREE_AUCTION';
export const SUCCESS_PUT_ITEM_FREE_AUCTION = 'SUCCESS_PUT_ITEM_FREE_AUCTION';
export const FAIL_PUT_ITEM_FREE_AUCTION = 'FAIL_PUT_ITEM_FREE_AUCTION';
export const SUCCESS_GET_VENDOR_OPTIONS_FREE_AUCTION = 'SUCCESS_GET_VENDOR_OPTIONS_FREE_AUCTION';
export const FAIL_GET_VENDOR_OPTIONS_FREE_AUCTION = 'FAIL_GET_VENDOR_OPTIONS_FREE_AUCTION';