export const SUCCESS_FETCH_CREATE_LOA = 'SUCCESS_FETCH_CREATE_LOA';
export const FAIL_FETCH_CREATE_LOA = 'FAIL_FETCH_CREATE_LOA';
export const SUCCESS_SHOW_GENERATE_PDF_CREATE_LOA = 'SUCCESS_SHOW_GENERATE_PDF_CREATE_LOA';
export const FAIL_SHOW_GENERATE_PDF_CREATE_LOA = 'FAIL_SHOW_GENERATE_PDF_CREATE_LOA';
export const SUCCESS_SHOW_DETAIL_PO_LOA = 'SUCCESS_SHOW_DETAIL_PO_LOA';
export const FAIL_SHOW_DETAIL_PO_LOA = 'FAIL_SHOW_DETAIL_PO_LOA';
export const SUCCESS_APPROVAL_PO_LOA = 'SUCCESS_APPROVAL_PO_LOA';
export const FAIL_APPROVAL_PO_LOA = 'FAIL_APPROVAL_PO_LOA';
