export const SUCCESS_FETCH_EXPEDITING = 'SUCCESS_FETCH_EXPEDITING';
export const FAIL_FETCH_EXPEDITING = 'FAIL_FETCH_EXPEDITING';
export const SUCCESS_SHOW_EXPEDITING = 'SUCCESS_SHOW_EXPEDITING';
export const FAIL_SHOW_EXPEDITING = 'FAIL_SHOW_EXPEDITING';
