export const SUCCESS_FETCH_MATERIAL_SERVICE_REQUEST = 'SUCCESS_FETCH_MATERIAL_SERVICE_REQUEST';
export const FAIL_FETCH_MATERIAL_SERVICE_REQUEST = 'FAIL_FETCH_MATERIAL_SERVICE_REQUEST';
export const SUCCESS_SAVE_MATERIAL_SERVICE_REQUEST = 'SUCCESS_SAVE_MATERIAL_SERVICE_REQUEST';
export const FAIL_SAVE_MATERIAL_SERVICE_REQUEST = 'FAIL_SAVE_MATERIAL_SERVICE_REQUEST';
export const SUCCESS_SHOW_MATERIAL_SERVICE_REQUEST = 'SUCCESS_SHOW_MATERIAL_SERVICE_REQUEST';
export const FAIL_SHOW_MATERIAL_SERVICE_REQUEST = 'FAIL_SHOW_MATERIAL_SERVICE_REQUEST';
export const SUCCESS_UPDATE_MATERIAL_SERVICE_REQUEST = 'SUCCESS_UPDATE_MATERIAL_SERVICE_REQUEST';
export const FAIL_UPDATE_MATERIAL_SERVICE_REQUEST = 'FAIL_UPDATE_MATERIAL_SERVICE_REQUEST';
export const SUCCESS_DELETE_MATERIAL_SERVICE_REQUEST = 'SUCCESS_DELETE_MATERIAL_SERVICE_REQUEST';
export const FAIL_DELETE_MATERIAL_SERVICE_REQUEST = 'FAIL_DELETE_MATERIAL_SERVICE_REQUEST';
export const SUCCESS_HISTORY_MATERIAL_SERVICE_REQUEST = 'SUCCESS_HISTORY_MATERIAL_SERVICE_REQUEST';
export const FAIL_HISTORY_MATERIAL_SERVICE_REQUEST = 'FAIL_HISTORY_MATERIAL_SERVICE_REQUEST';

//PR Manual
export const SUCCESS_SUBMIT_PR_MANUAL = 'SUCCESS_SUBMIT_PR_MANUAL';
export const FAIL_SUBMIT_PR_MANUAL = 'FAIL_SUBMIT_PR_MANUAL';
export const SUCCESS_APPROVAL_PR_MANUAL = 'SUCCESS_APPROVAL_PR_MANUAL';
export const FAIL_APPROVAL_PR_MANUAL = 'FAIL_APPROVAL_PR_MANUAL';
