export const SUCCESS_FETCH_MONITORING_MRSR = 'SUCCESS_FETCH_MONITORING_MRSR';
export const FAIL_FETCH_MONITORING_MRSR = 'FAIL_FETCH_MONITORING_MRSR';
export const SUCCESS_SHOW_MONITORING_MRSR = 'SUCCESS_SHOW_MONITORING_MRSR';
export const FAIL_SHOW_MONITORING_MRSR = 'FAIL_SHOW_MONITORING_MRSR';
export const SUCCESS_UPDATE_MONITORING_MRSR = 'SUCCESS_UPDATE_MONITORING_MRSR';
export const FAIL_UPDATE_MONITORING_MRSR = 'FAIL_UPDATE_MONITORING_MRSR';
