export const SUCCESS_FETCH_MONITORING_TENDER_BUYER = 'SUCCESS_FETCH_MONITORING_TENDER_BUYER';
export const FAIL_FETCH_MONITORING_TENDER_BUYER = 'FAIL_FETCH_MONITORING_TENDER_BUYER';
export const SUCCESS_FETCH_MONITORING_TENDER_BUYER_DETAIL = 'SUCCESS_FETCH_MONITORING_TENDER_BUYER_DETAIL';
export const FAIL_FETCH_MONITORING_TENDER_BUYER_DETAIL = 'FAIL_FETCH_MONITORING_TENDER_BUYER_DETAIL';
export const SUCCESS_SHOW_VENDOR_PANEL = 'SUCCESS_SHOW_VENDOR_PANEL';
export const FAIL_SHOW_VENDOR_PANEL = 'FAIL_SHOW_VENDOR_PANEL';
export const SUCCESS_UPDATE_DOKUMEN_PENGADAAN = 'SUCCESS_UPDATE_DOKUMEN_PENGADAAN';
export const FAIL_UPDATE_DOKUMEN_PENGADAAN = 'FAIL_UPDATE_DOKUMEN_PENGADAAN';
export const SUCCESS_UPDATE_PROPOSAL_TENDER_JADWAL = 'SUCCESS_UPDATE_PROPOSAL_TENDER_JADWAL';
export const FAIL_UPDATE_PROPOSAL_TENDER_JADWAL = 'FAIL_UPDATE_PROPOSAL_TENDER_JADWAL';
export const SUCCESS_FETCH_HISTORY_JADWAL_TENDER = 'SUCCESS_FETCH_HISTORY_JADWAL_TENDER';
export const FAIL_FETCH_HISTORY_JADWAL_TENDER = 'FAIL_FETCH_HISTORY_JADWAL_TENDER';
export const SUCCESS_DOWNLOAD_AWARDING_BERITA_ACARA = 'SUCCESS_DOWNLOAD_AWARDING_BERITA_ACARA';
export const FAIL_DOWNLOAD_AWARDING_BERITA_ACARA = 'FAIL_DOWNLOAD_AWARDING_BERITA_ACARA';
export const SUCCESS_DOWNLOAD_PO_BERITA_ACARA = 'SUCCESS_DOWNLOAD_PO_BERITA_ACARA';
export const FAIL_DOWNLOAD_PO_BERITA_ACARA = 'FAIL_DOWNLOAD_PO_BERITA_ACARA';
export const SUCCESS_FETCH_ARSIP_TENDER_MONITORING = 'SUCCESS_FETCH_ARSIP_TENDER_MONITORING';
export const FAIL_FETCH_ARSIP_TENDER_MONITORING = 'FAIL_FETCH_ARSIP_TENDER_MONITORING';
export const SUCCESS_SAVE_ARSIP_TENDER_MONITORING = 'SUCCESS_SAVE_ARSIP_TENDER_MONITORING';
export const FAIL_SAVE_ARSIP_TENDER_MONITORING = 'FAIL_SAVE_ARSIP_TENDER_MONITORING';
export const SUCCESS_DELETE_ARSIP_TENDER_MONITORING = 'SUCCESS_DELETE_ARSIP_TENDER_MONITORING';
export const FAIL_DELETE_ARSIP_TENDER_MONITORING = 'FAIL_DELETE_ARSIP_TENDER_MONITORING';
export const SUCCESS_DOWNLOAD_MONITORING_TENDER = 'SUCCESS_DOWNLOAD_MONITORING_TENDER';
export const FAIL_DOWNLOAD_MONITORING_TENDER = 'FAIL_DOWNLOAD_MONITORING_TENDER';
export const SUCCESS_DOWNLOAD_RFQ = 'SUCCESS_DOWNLOAD_RFQ';
export const FAIL_DOWNLOAD_RFQ = 'FAIL_DOWNLOAD_RFQ';
export const SUCCESS_DOWNLOAD_PAKTA_INTEGRITAS_TENDER = 'SUCCESS_DOWNLOAD_PAKTA_INTEGRITAS_TENDER';
export const FAIL_DOWNLOAD_PAKTA_INTEGRITAS_TENDER = 'FAIL_DOWNLOAD_PAKTA_INTEGRITAS_TENDER';
export const SUCCESS_SHOW_PO_OUTSTANDING = 'SUCCESS_SHOW_PO_OUTSTANDING';
export const FAIL_SHOW_PO_OUTSTANDING = 'FAIL_SHOW_PO_OUTSTANDING';
export const SUCCESS_DOWNLOAD_MONITORING_TENDER_BUYER_DETAIL = 'SUCCESS_DOWNLOAD_MONITORING_TENDER_BUYER_DETAIL';
export const FAIL_DOWNLOAD_MONITORING_TENDER_BUYER_DETAIL = 'FAIL_DOWNLOAD_MONITORING_TENDER_BUYER_DETAIL';
export const SUCCESS_SUBMIT_EXTEND_JADWAL_MONITORING_TENDER = 'SUCCESS_SUBMIT_EXTEND_JADWAL_MONITORING_TENDER';
export const FAIL_SUBMIT_EXTEND_JADWAL_MONITORING_TENDER = 'FAIL_SUBMIT_EXTEND_JADWAL_MONITORING_TENDER';
export const SUCCESS_APPROVE_EXTEND_JADWAL_MONITORING_TENDER = 'SUCCESS_APPROVE_EXTEND_JADWAL_MONITORING_TENDER';
export const FAIL_APPROVE_EXTEND_JADWAL_MONITORING_TENDER = 'FAIL_APPROVE_EXTEND_JADWAL_MONITORING_TENDER';






