export const SUCCESS_FETCH_VENDOR_QUOTATION = 'SUCCESS_FETCH_VENDOR_QUOTATION';
export const FAIL_FETCH_VENDOR_QUOTATION = 'FAIL_FETCH_VENDOR_QUOTATION';
export const SUCCESS_GET_DETAIL_VENDOR_QUOTATION = 'SUCCESS_GET_DETAIL_VENDOR_QUOTATION';
export const FAIL_GET_DETAIL_VENDOR_QUOTATION = 'FAIL_GET_DETAIL_VENDOR_QUOTATION';
export const SUCCESS_SUBMIT_VENDOR_QUOTATION = 'SUCCESS_SUBMIT_VENDOR_QUOTATION';
export const FAIL_SUBMIT_VENDOR_QUOTATION = 'FAIL_SUBMIT_VENDOR_QUOTATION';
export const SUCCESS_GET_VENDOR_QUOTATION = 'SUCCESS_GET_VENDOR_QUOTATION';
export const FAIL_GET_VENDOR_QUOTATION = 'FAIL_GET_VENDOR_QUOTATION';
export const SUCCESS_UPDATE_VENDOR_QUOTATION = 'SUCCESS_UPDATE_VENDOR_QUOTATION';
export const FAIL_UPDATE_VENDOR_QUOTATION = 'FAIL_UPDATE_VENDOR_QUOTATION';
export const SUCCESS_SUBMIT_REGISTER_VENDOR_QUOTATION = 'SUCCESS_SUBMIT_REGISTER_VENDOR_QUOTATION';
export const FAIL_SUBMIT_REGISTER_VENDOR_QUOTATION = 'FAIL_SUBMIT_REGISTER_VENDOR_QUOTATION';

//PENAWARAN TERKIRIM
export const SUCCESS_FETCH_DETAIL_PENAWARAN_TERKIRIM = 'SUCCESS_FETCH_DETAIL_PENAWARAN_TERKIRIM';
export const FAIL_FETCH_DETAIL_PENAWARAN_TERKIRIM = 'FAIL_FETCH_DETAIL_PENAWARAN_TERKIRIM';
export const SUCCESS_FETCH_PENAWARAN_TERKIRIM = 'SUCCESS_FETCH_PENAWARAN_TERKIRIM';
export const FAIL_FETCH_PENAWARAN_TERKIRIM = 'FAIL_FETCH_PENAWARAN_TERKIRIM';
export const SUCCESS_GET_PENAWARAN_TERKIRIM_VENDOR_QUOTATION = 'SUCCESS_GET_PENAWARAN_TERKIRIM_VENDOR_QUOTATION';
export const FAIL_GET_PENAWARAN_TERKIRIM_VENDOR_QUOTATION = 'FAIL_GET_PENAWARAN_TERKIRIM_VENDOR_QUOTATION';
export const SUCCESS_FIND_QUOTATION_VENDOR = 'SUCCESS_FIND_QUOTATION_VENDOR';
export const FAIL_FIND_QUOTATION_VENDOR = 'FAIL_FIND_QUOTATION_VENDOR';