export const SUCCESS_FETCH_UNDANGAN_TENDER = 'SUCCESS_FETCH_UNDANGAN_TENDER';
export const FAIL_FETCH_UNDANGAN_TENDER = 'FAIL_FETCH_UNDANGAN_TENDER';
export const SUCCESS_FETCH_UNDANGAN_TENDER_AKTIF = 'SUCCESS_FETCH_UNDANGAN_TENDER_AKTIF';
export const FAIL_FETCH_UNDANGAN_TENDER_AKTIF = 'FAIL_FETCH_UNDANGAN_TENDER_AKTIF';