export const SUCCESS_FETCH_ANNOUNCEMENT = 'SUCCESS_FETCH_ANNOUNCEMENT';
export const FAIL_FETCH_ANNOUNCEMENT = 'FAIL_FETCH_ANNOUNCEMENT';
export const SUCCESS_SAVE_ANNOUNCEMENT = 'SUCCESS_SAVE_ANNOUNCEMENT';
export const FAIL_SAVE_ANNOUNCEMENT = 'FAIL_SAVE_ANNOUNCEMENT';
export const SUCCESS_SHOW_ANNOUNCEMENT = 'SUCCESS_SHOW_ANNOUNCEMENT';
export const FAIL_SHOW_ANNOUNCEMENT = 'FAIL_SHOW_ANNOUNCEMENT';
export const SUCCESS_UPDATE_ANNOUNCEMENT = 'SUCCESS_UPDATE_ANNOUNCEMENT';
export const FAIL_UPDATE_ANNOUNCEMENT = 'FAIL_UPDATE_ANNOUNCEMENT';
export const SUCCESS_DELETE_ANNOUNCEMENT = 'SUCCESS_DELETE_ANNOUNCEMENT';
export const FAIL_DELETE_ANNOUNCEMENT = 'FAIL_DELETE_ANNOUNCEMENT';

// konfigurasi pendaftaran vendor mandiri
export const SUCCESS_FETCH_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI = 'SUCCESS_FETCH_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI';
export const FAIL_FETCH_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI = 'FAIL_FETCH_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI';
export const SUCCESS_SAVE_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI = 'SUCCESS_SAVE_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI';
export const FAIL_SAVE_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI = 'FAIL_SAVE_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI';
export const SUCCESS_FETCH_SHOW_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI = 'SUCCESS_FETCH_SHOW_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI';
export const FAIL_FETCH_SHOW_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI = 'FAIL_FETCH_SHOW_KONFIGURASI_PENDAFTARAN_VENDOR_MANDIRI';