export const SUCCESS_FETCH_PROFIT_CENTER = 'SUCCESS_FETCH_PROFIT_CENTER';
export const FAIL_FETCH_PROFIT_CENTER = 'FAIL_FETCH_PROFIT_CENTER';
export const SUCCESS_SYNC_PROFIT_CENTER = 'SUCCESS_SYNC_PROFIT_CENTER';
export const FAIL_SYNC_PROFIT_CENTER = 'FAIL_SYNC_PROFIT_CENTER';
// export const SUCCESS_SAVE_NPWP = 'SUCCESS_SAVE_NPWP';
// export const FAIL_SAVE_NPWP = 'FAIL_SAVE_NPWP';
// export const SUCCESS_SHOW_NPWP = 'SUCCESS_SHOW_NPWP';
// export const FAIL_SHOW_NPWP = 'FAIL_SHOW_NPWP';
// export const SUCCESS_UPDATE_NPWP = 'SUCCESS_UPDATE_NPWP';
// export const FAIL_UPDATE_NPWP = 'FAIL_UPDATE_NPWP';
// export const SUCCESS_DELETE_NPWP = 'SUCCESS_DELETE_NPWP';
// export const FAIL_DELETE_NPWP = 'FAIL_DELETE_NPWP';

