export const SUCCESS_FETCH_MASTER_VPR = 'SUCCESS_FETCH_MASTER_VPR';
export const FAIL_FETCH_MASTER_VPR = 'FAFAIL_FETCH_MASTER_VPR';
export const SUCCESS_SYNC_MASTER_VPR = 'SUCCESS_SYNC_MASTER_VPR'
export const FAIL_SYNC_MASTER_VPR = 'FAIL_SYNC_MASTER_VPR'


