export const SUCCESS_FETCH_MASTER_KPI = 'SUCCESS_FETCH_MASTER_KPI';
export const FAIL_FETCH_MASTER_KPI = 'FAIL_FETCH_MASTER_KPI';
export const SUCCESS_GET_MASTER_KPI = 'SUCCESS_GET_MASTER_KPI';
export const FAIL_GET_MASTER_KPI = 'FAIL_GET_MASTER_KPI';
export const SUCCESS_STORE_MASTER_KPI = 'SUCCESS_STORE_MASTER_KPI';
export const FAIL_STORE_MASTER_KPI = 'FAIL_STORE_MASTER_KPI';
export const SUCCESS_DELETE_MASTER_KPI = 'SUCCESS_DELETE_MASTER_KPI';
export const FAIL_DELETE_MASTER_KPI = 'FAIL_DELETE_MASTER_KPI';