export const SUCCESS_FETCH_POSTCAL_CODE = 'SUCCESS_FETCH_POSTCAL_CODE';
export const FAIL_FETCH_POSTCAL_CODE = 'FAIL_FETCH_POSTCAL_CODE';
export const SUCCESS_SAVE_POSTCAL_CODE = 'SUCCESS_SAVE_POSTCAL_CODE';
export const FAIL_SAVE_POSTCAL_CODE = 'FAIL_SAVE_POSTCAL_CODE';
export const SUCCESS_SHOW_POSTCAL_CODE = 'SUCCESS_SHOW_POSTCAL_CODE';
export const FAIL_SHOW_POSTCAL_CODE = 'FAIL_SHOW_POSTCAL_CODE';
export const SUCCESS_UPDATE_POSTCAL_CODE = 'SUCCESS_UPDATE_POSTCAL_CODE';
export const FAIL_UPDATE_POSTCAL_CODE = 'FAIL_UPDATE_POSTCAL_CODE';
export const SUCCESS_DELETE_POSTCAL_CODE = 'SUCCESS_DELETE_POSTCAL_CODE';
export const FAIL_DELETE_POSTCAL_CODE = 'FAIL_DELETE_POSTCAL_CODE';


export const SUCCESS_FETCH_POSTCAL_CODE_MAPPING = 'SUCCESS_FETCH_POSTCAL_CODE_MAPPING';
export const FAIL_FETCH_POSTCAL_CODE_MAPPING = 'FAIL_FETCH_POSTCAL_CODE_MAPPING';
export const SUCCESS_SAVE_POSTCAL_CODE_MAPPING = 'SUCCESS_SAVE_POSTCAL_CODE_MAPPING';
export const FAIL_SAVE_POSTCAL_CODE_MAPPING = 'FAIL_SAVE_POSTCAL_CODE_MAPPING';
export const SUCCESS_SHOW_POSTCAL_CODE_MAPPING = 'SUCCESS_SHOW_POSTCAL_CODE_MAPPING';
export const FAIL_SHOW_POSTCAL_CODE_MAPPING = 'FAIL_SHOW_POSTCAL_CODE_MAPPING';
export const SUCCESS_UPDATE_POSTCAL_CODE_MAPPING = 'SUCCESS_UPDATE_POSTCAL_CODE_MAPPING';
export const FAIL_UPDATE_POSTCAL_CODE_MAPPING = 'FAIL_UPDATE_POSTCAL_CODE_MAPPING';
export const SUCCESS_DELETE_POSTCAL_CODE_MAPPING = 'SUCCESS_DELETE_POSTCAL_CODE_MAPPING';
export const FAIL_DELETE_POSTCAL_CODE_MAPPING = 'FAIL_DELETE_POSTCAL_CODE_MAPPING';