export const SUCCESS_GUEST_UPLOAD = 'SUCCESS_GUEST_UPLOAD';
export const FAIL_GUEST_UPLOAD = 'FAIL_GUEST_UPLOAD';
export const SUCCESS_UPLOAD_FILE = 'SUCCESS_UPLOAD_FILE';
export const FAIL_UPLOAD_FILE = 'FAIL_UPLOAD_FILE';
export const SUCCESS_UPLOAD_FILE_MIGRASI = 'SUCCESS_UPLOAD_FILE_MIGRASI';
export const FAIL_UPLOAD_FILE_MIGRASI = 'FAIL_UPLOAD_FILE_MIGRASI';
export const SUCCESS_MERGE_DOCUMENT = 'SUCCESS_MERGE_DOCUMENT';
export const FAIL_MERGE_DOCUMENT = 'FAIL_MERGE_DOCUMENT';
